"""Add admin authentication and content CMS"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision = '222b971ed0e6'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_auth_throttles',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('admins',
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('branches',
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('short_name', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('areas', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='draft', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft','published','archived')", name='ck_branches_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_branches_status'), 'branches', ['status'], unique=False)
    op.create_table('career_domains',
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('what_you_do', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('core_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('supporting_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('useful_subjects', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tools', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('technologies', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('suitable_for', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('challenges', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('programming_level', sa.String(length=10), nullable=False),
    sa.Column('mathematics_level', sa.String(length=10), nullable=False),
    sa.Column('roadmap', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='draft', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("mathematics_level IN ('Low','Moderate','High')", name='ck_domain_mathematics'),
    sa.CheckConstraint("programming_level IN ('Low','Moderate','High')", name='ck_domain_programming'),
    sa.CheckConstraint("status IN ('draft','published','archived')", name='ck_career_domains_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_career_domains_status'), 'career_domains', ['status'], unique=False)
    op.create_table('site_content',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='draft', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft','published','archived')", name='ck_site_content_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index(op.f('ix_site_content_status'), 'site_content', ['status'], unique=False)
    op.create_table('admin_challenges',
    sa.Column('admin_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('otp_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_admin_challenges_admin_id'), 'admin_challenges', ['admin_id'], unique=False)
    op.create_index(op.f('ix_admin_challenges_expires_at'), 'admin_challenges', ['expires_at'], unique=False)
    op.create_table('admin_sessions',
    sa.Column('admin_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_admin_sessions_admin_id'), 'admin_sessions', ['admin_id'], unique=False)
    op.create_index(op.f('ix_admin_sessions_expires_at'), 'admin_sessions', ['expires_at'], unique=False)
    op.create_table('branch_domains',
    sa.Column('branch_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('domain_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['domain_id'], ['career_domains.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('branch_id', 'domain_id')
    )
    op.create_table('career_roles',
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('domain_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('responsibilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('useful_subjects', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tools', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('technologies', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('programming_level', sa.String(length=10), nullable=False),
    sa.Column('mathematics_level', sa.String(length=10), nullable=False),
    sa.Column('roadmap', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('interview_topics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('example_projects', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='draft', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("mathematics_level IN ('Low','Moderate','High')", name='ck_role_mathematics'),
    sa.CheckConstraint("programming_level IN ('Low','Moderate','High')", name='ck_role_programming'),
    sa.CheckConstraint("status IN ('draft','published','archived')", name='ck_career_roles_status'),
    sa.ForeignKeyConstraint(['domain_id'], ['career_domains.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_career_roles_domain_id'), 'career_roles', ['domain_id'], unique=False)
    op.create_index(op.f('ix_career_roles_status'), 'career_roles', ['status'], unique=False)
    op.create_table('semesters',
    sa.Column('academic_level', sa.String(length=2), nullable=False),
    sa.Column('branch_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='draft', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(academic_level='P1' AND branch_id IS NULL) OR (academic_level='E1' AND branch_id IS NOT NULL)", name='ck_semester_branch'),
    sa.CheckConstraint("academic_level IN ('P1','E1')", name='ck_semester_level'),
    sa.CheckConstraint("status IN ('draft','published','archived')", name='ck_semesters_status'),
    sa.CheckConstraint('number BETWEEN 1 AND 12', name='ck_semester_number'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch_id', 'number', name='uq_semester_branch_number')
    )
    op.create_index(op.f('ix_semesters_academic_level'), 'semesters', ['academic_level'], unique=False)
    op.create_index(op.f('ix_semesters_branch_id'), 'semesters', ['branch_id'], unique=False)
    op.create_index(op.f('ix_semesters_status'), 'semesters', ['status'], unique=False)
    op.create_index('uq_semester_p1', 'semesters', ['academic_level', 'number'], unique=True, postgresql_where=sa.text('branch_id IS NULL'))
    op.create_table('branch_roles',
    sa.Column('branch_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('role_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['role_id'], ['career_roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('branch_id', 'role_id')
    )
    op.create_table('domain_related_roles',
    sa.Column('domain_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('role_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['career_domains.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['role_id'], ['career_roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('domain_id', 'role_id')
    )
    op.create_table('labs',
    sa.Column('semester_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='draft', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft','published','archived')", name='ck_labs_status'),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('semester_id', 'slug', name='uq_lab_semester_slug')
    )
    op.create_index(op.f('ix_labs_semester_id'), 'labs', ['semester_id'], unique=False)
    op.create_index(op.f('ix_labs_slug'), 'labs', ['slug'], unique=False)
    op.create_index(op.f('ix_labs_status'), 'labs', ['status'], unique=False)
    op.create_table('subjects',
    sa.Column('semester_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='draft', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft','published','archived')", name='ck_subjects_status'),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('semester_id', 'slug', name='uq_subject_semester_slug')
    )
    op.create_index(op.f('ix_subjects_semester_id'), 'subjects', ['semester_id'], unique=False)
    op.create_index(op.f('ix_subjects_slug'), 'subjects', ['slug'], unique=False)
    op.create_index(op.f('ix_subjects_status'), 'subjects', ['status'], unique=False)
    op.create_table('experiments',
    sa.Column('lab_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('experiment_number', sa.Integer(), nullable=True),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('theory', sa.Text(), nullable=False),
    sa.Column('apparatus', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('procedure', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expected_result', sa.Text(), nullable=False),
    sa.Column('precautions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('video_type', sa.String(length=16), nullable=True),
    sa.Column('video_url', sa.Text(), nullable=True),
    sa.Column('duration', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='draft', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft','published','archived')", name='ck_experiments_status'),
    sa.CheckConstraint("video_type IS NULL OR video_type IN ('youtube','mp4','external')", name='ck_experiment_video'),
    sa.ForeignKeyConstraint(['lab_id'], ['labs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lab_id', 'slug', name='uq_experiment_lab_slug')
    )
    op.create_index(op.f('ix_experiments_lab_id'), 'experiments', ['lab_id'], unique=False)
    op.create_index(op.f('ix_experiments_slug'), 'experiments', ['slug'], unique=False)
    op.create_index(op.f('ix_experiments_status'), 'experiments', ['status'], unique=False)
    op.create_table('reference_books',
    sa.Column('subject_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('authors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('edition', sa.String(length=100), nullable=False),
    sa.Column('publisher', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('resource_url', sa.Text(), nullable=True),
    sa.Column('availability', sa.String(length=20), nullable=False),
    sa.Column('seed_key', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='draft', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("availability IN ('coming_soon','available')", name='ck_book_availability'),
    sa.CheckConstraint("status IN ('draft','published','archived')", name='ck_reference_books_status'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seed_key')
    )
    op.create_index(op.f('ix_reference_books_status'), 'reference_books', ['status'], unique=False)
    op.create_index(op.f('ix_reference_books_subject_id'), 'reference_books', ['subject_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    raise RuntimeError('Review and approve a data-preserving rollback before downgrading.')
