"""add level-specific resources and student problems"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision = '41f606784098'
down_revision = '222b971ed0e6'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faculty_subjects',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='draft', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft','published','archived')", name='ck_faculty_subjects_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_faculty_subjects_status'), 'faculty_subjects', ['status'], unique=False)
    op.create_table('information_rooms',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('room_number', sa.String(length=80), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=False),
    sa.Column('floor', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='draft', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft','published','archived')", name='ck_information_rooms_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_number', 'name', name='uq_room_number_name')
    )
    op.create_index(op.f('ix_information_rooms_status'), 'information_rooms', ['status'], unique=False)
    op.create_table('student_problems',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('academic_level', sa.String(length=2), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='open', nullable=False),
    sa.Column('author_identifier', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("academic_level IN ('P1','E1')", name='ck_problem_academic_level'),
    sa.CheckConstraint("priority IN ('low','medium','high')", name='ck_problem_priority'),
    sa.CheckConstraint("status IN ('open','in_progress','resolved','archived')", name='ck_problem_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_problems_academic_level'), 'student_problems', ['academic_level'], unique=False)
    op.create_index(op.f('ix_student_problems_priority'), 'student_problems', ['priority'], unique=False)
    op.create_index(op.f('ix_student_problems_status'), 'student_problems', ['status'], unique=False)
    op.create_index('ix_student_problems_created_at', 'student_problems', ['created_at'], unique=False)
    op.create_table('career_resources',
    sa.Column('resource_type', sa.String(length=12), nullable=False),
    sa.Column('branch_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.Column('supporting_url', sa.Text(), nullable=True),
    sa.Column('storage_type', sa.String(length=20), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='draft', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("resource_type IN ('domain','job')", name='ck_career_resource_type'),
    sa.CheckConstraint("status IN ('draft','published','archived')", name='ck_career_resources_status'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_resources_branch_id'), 'career_resources', ['branch_id'], unique=False)
    op.create_index(op.f('ix_career_resources_resource_type'), 'career_resources', ['resource_type'], unique=False)
    op.create_index(op.f('ix_career_resources_status'), 'career_resources', ['status'], unique=False)
    op.create_table('faculty_members',
    sa.Column('subject_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('designation', sa.String(length=200), nullable=False),
    sa.Column('mobile_number', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('room_number', sa.String(length=80), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='draft', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft','published','archived')", name='ck_faculty_members_status'),
    sa.ForeignKeyConstraint(['subject_id'], ['faculty_subjects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faculty_members_status'), 'faculty_members', ['status'], unique=False)
    op.create_index(op.f('ix_faculty_members_subject_id'), 'faculty_members', ['subject_id'], unique=False)
    op.create_table('problem_reactions',
    sa.Column('problem_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('student_identifier', sa.String(length=64), nullable=False),
    sa.Column('reaction', sa.String(length=8), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("reaction IN ('like','dislike')", name='ck_problem_reaction'),
    sa.ForeignKeyConstraint(['problem_id'], ['student_problems.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('problem_id', 'student_identifier', name='uq_problem_student_reaction')
    )
    op.create_index(op.f('ix_problem_reactions_problem_id'), 'problem_reactions', ['problem_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    raise RuntimeError('Review and approve a data-preserving rollback before downgrading.')
