-- Generated by npm run db:academic from src/config/academic.ts. Do not edit.
insert into public.academic_config (id, current_p1_batch)
values (true, 26)
on conflict (id) do update set current_p1_batch = excluded.current_p1_batch;
